### ISSUE TITLE
[Misc] Add type hints

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#558]
## Summary

Type hints are a thing, and I think it's beneficial to everyone that we have type hints everywhere, variables included. Since this should not functionally impact anything, we can do this on a per-cog basis.

## Tasks

- [ ] #566
- [ ] [Avatar] Add type hints
- [ ] [Birthday] Add type hints
- [ ] [Catgirl] Add type hints
- [ ] [GoodSmileInfo] Add type hints
- [ ] [Heartbeat] Add type hints
- [ ] [Highlight] Add type hints
- [x] #563
- [x] #633
- [ ] [RoleAssigner] Add type hints
- [ ] [RSS] Add type hints
- [ ] [ServerManage] Add type hints
- [ ] [Spoilers] Add type hints
- [ ] [Tags] Add type hints
- [ ] [TempChannels] Add type hints
- [ ] [Triggered] Add type hints
- [ ] [Welcome] Add type hints
- [ ] [WordFilter] Add type hints
- [ ] [YOURLSClient] Add type hints

**Comment by quachtridat** [comment]
Our cogs include:
- [ ] AfterHours
- [ ] Avatar
- [ ] Birthday
- [ ] Catgirl
- [ ] GoodSmileInfo
- [ ] Heartbeat
- [ ] Highlight
- [ ] QRChecker
- [ ] Respects
- [ ] RoleAssigner
- [ ] RSS
- [ ] ServerManage
- [ ] Spoilers
- [ ] Tags
- [ ] TempChannels
- [ ] Triggered
- [ ] Welcome
- [ ] WordFilter
- [ ] YOURLSClient
